# Generated by Django 3.0 on 2020-01-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_text', models.CharField(max_length=200)),
                ('thread_creator', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('thread_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizbank.ThreadTopic')),
            ],
        ),
    ]
