# Generated by Django 3.0 on 2020-01-15 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0002_threadpost_threadtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadtopic',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 20, 20, 32, 533451, tzinfo=utc), verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='threadtopic',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threadtopic',
            name='summary_text',
            field=models.CharField(default='this is a default summary', max_length=200),
        ),
    ]
