# Generated by Django 3.0 on 2020-01-31 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0005_auto_20200127_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadtopic',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 20, 54, 50, 721154, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
