# Generated by Django 3.0 on 2020-05-13 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0010_auto_20200210_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUserProfilePics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='threadtopic',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 23, 46, 57, 15916, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
