# Generated by Django 3.0 on 2020-05-13 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0011_auto_20200513_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForumUserProfilePics',
            new_name='ForumUserProfilePic',
        ),
        migrations.AlterField(
            model_name='threadtopic',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 23, 51, 28, 691912, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
