# Generated by Django 3.0 on 2020-05-16 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0013_auto_20200516_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 1, 13, 45, 759776, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='last_updated_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 1, 13, 45, 759793, tzinfo=utc), verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='parent_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='threadtopic',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 1, 13, 45, 758331, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
