# Generated by Django 3.0 on 2020-02-19 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0013_auto_20200219_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadtopic',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 5, 22, 48, 194271, tzinfo=utc), verbose_name='last updated'),
        ),
    ]
